import {
  referenceManifestEntrySchema,
  type ReferenceManifestEntry,
} from "../features/references/schema";

export const referenceManifest: ReferenceManifestEntry[] = [
  {
    sourceId: "ietf-rfc9111-http-caching",
    canonicalUrl: "https://www.rfc-editor.org/rfc/rfc9111.txt",
    publisher: "ietf",
    documentTitle: "RFC 9111: HTTP Caching",
    category: "caching",
    topics: ["cache-control", "shared-cache", "revalidation"],
    language: "en",
    expectedContentType: "rfc",
    sourceVersion: "RFC 9111",
    enabled: true,
  },
  {
    sourceId: "ietf-rfc9110-http-semantics",
    canonicalUrl: "https://www.rfc-editor.org/rfc/rfc9110.txt",
    publisher: "ietf",
    documentTitle: "RFC 9110: HTTP Semantics",
    category: "http",
    topics: ["redirects", "status-codes", "semantics"],
    language: "en",
    expectedContentType: "rfc",
    sourceVersion: "RFC 9110",
    enabled: true,
  },
  {
    sourceId: "ietf-rfc1034-dns-concepts",
    canonicalUrl: "https://www.rfc-editor.org/rfc/rfc1034.txt",
    publisher: "ietf",
    documentTitle: "RFC 1034: Domain Names — Concepts and Facilities",
    category: "dns",
    topics: ["cname", "resolver", "authoritative"],
    language: "en",
    expectedContentType: "rfc",
    sourceVersion: "RFC 1034",
    enabled: true,
  },
  {
    sourceId: "ietf-rfc4035-dnssec",
    canonicalUrl: "https://www.rfc-editor.org/rfc/rfc4035.txt",
    publisher: "ietf",
    documentTitle: "RFC 4035: DNSSEC Protocol Modifications",
    category: "dnssec",
    topics: ["authenticated-data", "validation", "resolver"],
    language: "en",
    expectedContentType: "rfc",
    sourceVersion: "RFC 4035",
    enabled: true,
  },
  {
    sourceId: "ietf-rfc5280-certificates",
    canonicalUrl: "https://www.rfc-editor.org/rfc/rfc5280.txt",
    publisher: "ietf",
    documentTitle: "RFC 5280: Internet X.509 PKI Certificate Profile",
    category: "certificates",
    topics: ["hostname", "validity", "certificate"],
    language: "en",
    expectedContentType: "rfc",
    sourceVersion: "RFC 5280",
    enabled: true,
  },
  {
    sourceId: "cloudflare-cache-status",
    canonicalUrl: "https://developers.cloudflare.com/cache/concepts/cache-responses/",
    publisher: "cloudflare",
    documentTitle: "Cloudflare cache responses",
    category: "cdn",
    topics: ["cf-cache-status", "dynamic", "hit"],
    language: "en",
    expectedContentType: "html",
    enabled: true,
  },
  {
    sourceId: "cloudflare-workers-fetch",
    canonicalUrl: "https://developers.cloudflare.com/workers/runtime-apis/fetch/",
    publisher: "cloudflare",
    documentTitle: "Workers Fetch API",
    category: "cloudflare-workers-runtime",
    topics: ["fetch", "tls-metadata", "runtime-limitations"],
    language: "en",
    expectedContentType: "html",
    enabled: true,
  },
  {
    sourceId: "cloudflare-browser-run",
    canonicalUrl: "https://developers.cloudflare.com/browser-run/get-started/",
    publisher: "cloudflare",
    documentTitle: "Cloudflare Browser Run: Get started",
    category: "cloudflare-browser-run",
    topics: ["browser", "laboratory", "playwright"],
    language: "en",
    expectedContentType: "html",
    enabled: true,
  },
  {
    sourceId: "cloudflare-d1-limits",
    canonicalUrl: "https://developers.cloudflare.com/d1/platform/limits/",
    publisher: "cloudflare",
    documentTitle: "Cloudflare D1 limits",
    category: "cloudflare-d1",
    topics: ["d1", "limits", "rows"],
    language: "en",
    expectedContentType: "html",
    enabled: true,
  },
  {
    sourceId: "cloudflare-r2-workers-api",
    canonicalUrl: "https://developers.cloudflare.com/r2/api/workers/workers-api-reference/",
    publisher: "cloudflare",
    documentTitle: "R2 Workers API",
    category: "cloudflare-r2",
    topics: ["r2", "private-artifacts", "bindings"],
    language: "en",
    expectedContentType: "html",
    enabled: true,
  },
  {
    sourceId: "cloudflare-vectorize-metadata",
    canonicalUrl: "https://developers.cloudflare.com/vectorize/reference/metadata-filtering/",
    publisher: "cloudflare",
    documentTitle: "Vectorize metadata filtering",
    category: "cloudflare-vectorize",
    topics: ["vectorize", "metadata", "filtering"],
    language: "en",
    expectedContentType: "html",
    enabled: true,
  },
  {
    sourceId: "mdn-csp",
    canonicalUrl: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CSP",
    publisher: "mdn",
    documentTitle: "Content Security Policy",
    category: "security-headers",
    topics: ["csp", "frame-ancestors", "hardening"],
    language: "en",
    expectedContentType: "html",
    enabled: true,
  },
  {
    sourceId: "mdn-resource-timing",
    canonicalUrl: "https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming",
    publisher: "mdn",
    documentTitle: "PerformanceResourceTiming",
    category: "resource-loading",
    topics: ["resource-timing", "transfer-size", "cross-origin"],
    language: "en",
    expectedContentType: "html",
    enabled: true,
  },
  {
    sourceId: "owasp-secure-headers",
    canonicalUrl: "https://owasp.org/www-project-secure-headers/",
    publisher: "owasp",
    documentTitle: "OWASP Secure Headers Project",
    category: "security-headers",
    topics: ["security-headers", "hardening", "browser"],
    language: "en",
    expectedContentType: "html",
    enabled: true,
  },
  {
    sourceId: "web-dev-render-blocking",
    canonicalUrl: "https://web.dev/learn/performance/understanding-the-critical-path?hl=en",
    publisher: "web-dev",
    documentTitle: "Understanding the critical path",
    category: "performance",
    topics: ["render-blocking", "stylesheets", "critical-path"],
    language: "en",
    expectedContentType: "html",
    enabled: true,
  },
  {
    sourceId: "web-dev-third-party",
    canonicalUrl:
      "https://web.dev/articles/optimizing-content-efficiency-loading-third-party-javascript?hl=en",
    publisher: "web-dev",
    documentTitle: "Loading third-party JavaScript",
    category: "third-party-resources",
    topics: ["third-party", "javascript", "performance"],
    language: "en",
    expectedContentType: "html",
    enabled: true,
  },
  {
    sourceId: "cab-forum-baseline",
    canonicalUrl: "https://cabforum.org/working-groups/server/baseline-requirements/",
    publisher: "cab-forum",
    documentTitle: "CA/Browser Forum Baseline Requirements",
    category: "certificates",
    topics: ["certificate-policy", "san", "validity"],
    language: "en",
    expectedContentType: "html",
    enabled: true,
  },
].map((entry) => referenceManifestEntrySchema.parse(entry));

export function validateReferenceManifest(entries = referenceManifest): ReferenceManifestEntry[] {
  const parsed = entries.map((entry) => referenceManifestEntrySchema.parse(entry));
  const ids = new Set<string>();
  const urls = new Set<string>();
  for (const entry of parsed) {
    const url = new URL(entry.canonicalUrl);
    if (url.protocol !== "https:") throw new Error("Reference sources must use HTTPS.");
    if (ids.has(entry.sourceId))
      throw new Error(`Duplicate reference source ID: ${entry.sourceId}`);
    if (urls.has(url.href)) throw new Error(`Duplicate reference canonical URL: ${url.href}`);
    ids.add(entry.sourceId);
    urls.add(url.href);
  }
  return parsed;
}

export const referenceManifestById = new Map(
  validateReferenceManifest().map((entry) => [entry.sourceId, entry]),
);
